@startuml
title 商品問い合わせ〜購入（スイムレーン）

skinparam shadowing false
skinparam monochrome true
skinparam activity {
  BackgroundColor white
  BorderColor black
  FontColor black
}

|顧客|
start
:商品を問い合わせる;

|店員|
:在庫を確認する;

|販売管理システム|
:<<データストア>>\n在庫情報;

|店員|
:在庫状況を\n伝える;

|顧客|
if (在庫あり？) then (在庫あり)
  :商品を購入する;

  |店員|
  :システムに\n入力する;

  |販売管理システム|
  :<<データストア>>\n売上情報;

  |店員|
  :商品を渡す;

  |顧客|
  :商品を受け取る;
  stop

else (売り切れ)
  :売り切れ;
  stop
endif

@enduml
